// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAV3Xc3JCrR3X-ewKhkSZKTeGfdUxdR_Q',
    appId: '1:767416617750:web:72236503956d9be5169e37',
    messagingSenderId: '767416617750',
    projectId: 'efreigroupe3',
    authDomain: 'efreigroupe3.firebaseapp.com',
    storageBucket: 'efreigroupe3.appspot.com',
    measurementId: 'G-XYB838FNH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUUX311XB-2AKR0ELly9-KZq5jm4cOKA',
    appId: '1:767416617750:android:7dbf1cccf3d53f7a169e37',
    messagingSenderId: '767416617750',
    projectId: 'efreigroupe3',
    storageBucket: 'efreigroupe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBovPmcKb7Pslc56L-dZdj4AMVJ1vvTw9U',
    appId: '1:767416617750:ios:b4aba7413377ec91169e37',
    messagingSenderId: '767416617750',
    projectId: 'efreigroupe3',
    storageBucket: 'efreigroupe3.appspot.com',
    iosBundleId: 'com.example.efrei2023gr3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBovPmcKb7Pslc56L-dZdj4AMVJ1vvTw9U',
    appId: '1:767416617750:ios:c1f4d7701b5ded34169e37',
    messagingSenderId: '767416617750',
    projectId: 'efreigroupe3',
    storageBucket: 'efreigroupe3.appspot.com',
    iosBundleId: 'com.example.efrei2023gr3.RunnerTests',
  );
}
