// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwBGM3szFJArZZT_An_pGggxhkvdzCqtA',
    appId: '1:28365485652:web:4fd83bed4ecaaad4501fc1',
    messagingSenderId: '28365485652',
    projectId: 'flubereat',
    authDomain: 'flubereat.firebaseapp.com',
    storageBucket: 'flubereat.appspot.com',
    measurementId: 'G-TV2XVL2BFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLnZFUHSCzMx6xe3TdSDb4xntb3XoTXw',
    appId: '1:28365485652:android:486f72663cf38d37501fc1',
    messagingSenderId: '28365485652',
    projectId: 'flubereat',
    storageBucket: 'flubereat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQygKpR7xoyAROowf3UPi1WFGGeMlCyKc',
    appId: '1:28365485652:ios:0cdc2cfba0061294501fc1',
    messagingSenderId: '28365485652',
    projectId: 'flubereat',
    storageBucket: 'flubereat.appspot.com',
    iosBundleId: 'com.example.efrei2023gr3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQygKpR7xoyAROowf3UPi1WFGGeMlCyKc',
    appId: '1:28365485652:ios:892e34e4c5fa120f501fc1',
    messagingSenderId: '28365485652',
    projectId: 'flubereat',
    storageBucket: 'flubereat.appspot.com',
    iosBundleId: 'com.example.efrei2023gr3.RunnerTests',
  );
}
